# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_content', models.CharField(max_length=512)),
                ('core_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='NewsClassify',
            fields=[
                ('necl_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('necl_name', models.CharField(max_length=64, unique=True)),
                ('necl_create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_classify',
            },
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('nede_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('nede_create_date', models.DateField(auto_now_add=True)),
                ('nede_cover_img', models.URLField(default='')),
                ('nede_title', models.CharField(max_length=128)),
                ('nede_author', models.CharField(default='佚名', max_length=64)),
                ('nede_web_time', models.CharField(max_length=32, null=True)),
                ('nede_content', models.URLField(default='')),
                ('nede_browse', models.IntegerField(default=0)),
                ('nede_love', models.IntegerField(default=0)),
                ('nede_classify', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_server.NewsClassify', to_field='necl_name')),
            ],
            options={
                'db_table': 'news_detail',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usin_id', models.AutoField(primary_key=True, serialize=False)),
                ('usin_num', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('usin_pwd', models.CharField(max_length=18, verbose_name='密码')),
                ('usin_name', models.CharField(default='漫画小迷弟', max_length=32, verbose_name='昵称')),
                ('usin_sex', models.BooleanField()),
                ('usin_create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('usin_login_date', models.DateField(null=True, verbose_name='上次登录日期')),
                ('usin_phone', models.CharField(max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('usin_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('usin_sign', models.CharField(default='这个人很懒，什么也没留下', max_length=256, verbose_name='签名')),
                ('usin_count', models.IntegerField(default=0, verbose_name='登录次数')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserCollect',
            fields=[
                ('usco_usin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_server.UserInfo')),
                ('usco_create_date', models.DateField(auto_now_add=True)),
                ('usco_nede_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_server.NewsDetail')),
            ],
            options={
                'db_table': 'user_collect',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='core_nede_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_server.NewsDetail'),
        ),
        migrations.AddField(
            model_name='comment',
            name='core_usin_id',
            field=models.ManyToManyField(to='app_server.UserInfo'),
        ),
    ]
