# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='core_nede_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='core_nede_id',
            field=models.ManyToManyField(to='app_server.NewsDetail'),
        ),
    ]
