# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_auto_20170617_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='nede_classify',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_server.NewsClassify', to_field='necl_name'),
        ),
    ]
