# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0003_auto_20170617_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acco_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='文章标识'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acco_num',
            field=models.CharField(max_length=32, unique=True, verbose_name='账户'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acco_pwd',
            field=models.CharField(max_length=18, verbose_name='密码'),
        ),
    ]
